# syntax=docker/dockerfile:1.10-labs
# ------------------------------------------------------------
# S T A G E  B U I L D E R
# ------------------------------------------------------------
    ARG NODE_VERSION=22

    FROM node:${NODE_VERSION} AS builder

    WORKDIR /opt/app

    RUN npm install -g pnpm

    COPY package.json pnpm-lock.yaml ./

    RUN pnpm install

    COPY . .

# ------------------------------------------------------------
# S T A G E  D E V E L O P M E N T
# ------------------------------------------------------------
    FROM node:${NODE_VERSION}-alpine AS development

    WORKDIR /opt/app

    RUN npm install -g pnpm

    COPY --from=builder /opt/app .

    EXPOSE 3000

    CMD ["pnpm", "dev"]
