services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: homepage-dev
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/opt/app
      - node_modules:/opt/app/node_modules
      - /opt/app/.next
      - /opt/app/public
    ports:
      - "80:3000"
    env_file:
      - .env.local
    hostname: homepage-dev
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: homepage-prod
    ports:
      - "80:3000"
    env_file:
      - .env.local
    hostname: homepage-prod
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

volumes:
  node_modules:
